services:
  lanparty-fileserver:
    image: ghcr.io/r2unit/lanparty-fileserver:1.0.0
    container_name: lan-fileserver
    restart: unless-stopped 
    ports:
      - "80:80"
    environment:
        # Adjust the upload size to your desired size. This is so no one will upload their entire media collection :p
      - MAX_UPLOAD_SIZE_MB=250 

    volumes:
      - ./preloaded-games:/app/preloaded-games:ro
      - ./data/uploads:/app/uploads
      - ./data/downloads-log:/app/downloads-log
